version: '3'

services:
  demodb:
    image: postgres
    container_name: demodb
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
  app:
    build: .
    depends_on:
      - demodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://demodb:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"
